<a href="https://colab.research.google.com/github/Isgit67/CS7641/blob/master/00_pytorh_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

2. Create a random tensor with shape (7, 7).

In [4]:
# Import torch


# Create random tensor
random_tensor=torch.rand(size=(7,7))
random_tensor, random_tensor.dtype, random_tensor.device,random_tensor.shape, random_tensor.ndim

(tensor([[0.7468, 0.1742, 0.3709, 0.5187, 0.2124, 0.2923, 0.3649],
         [0.4523, 0.6888, 0.5499, 0.7101, 0.4173, 0.3338, 0.1912],
         [0.2047, 0.9382, 0.1160, 0.1932, 0.8400, 0.7984, 0.2788],
         [0.4768, 0.3369, 0.8858, 0.4618, 0.4124, 0.2127, 0.3857],
         [0.3938, 0.9955, 0.1011, 0.4903, 0.9395, 0.8070, 0.7762],
         [0.0087, 0.1093, 0.0253, 0.1029, 0.6729, 0.3439, 0.4130],
         [0.2023, 0.8703, 0.3648, 0.5378, 0.3121, 0.8038, 0.2117]]),
 torch.float32,
 device(type='cpu'),
 torch.Size([7, 7]),
 2)

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
second_random_tensor=torch.rand(size=(1,7))
output=torch.matmul(random_tensor, second_random_tensor.T)

print(random_tensor)
print(f"\nrandom_tensor: {random_tensor.shape}")

print(second_random_tensor)
print(f"\nsecond_random_tensor: {second_random_tensor.shape}")

print(f"\nsecond_random_tensor.T: {second_random_tensor.T.shape}")
print(second_random_tensor.T)

print(output)
print(f"\nOutput shape: {output.shape}")
# Perform matrix multiplication

tensor([[0.7468, 0.1742, 0.3709, 0.5187, 0.2124, 0.2923, 0.3649],
        [0.4523, 0.6888, 0.5499, 0.7101, 0.4173, 0.3338, 0.1912],
        [0.2047, 0.9382, 0.1160, 0.1932, 0.8400, 0.7984, 0.2788],
        [0.4768, 0.3369, 0.8858, 0.4618, 0.4124, 0.2127, 0.3857],
        [0.3938, 0.9955, 0.1011, 0.4903, 0.9395, 0.8070, 0.7762],
        [0.0087, 0.1093, 0.0253, 0.1029, 0.6729, 0.3439, 0.4130],
        [0.2023, 0.8703, 0.3648, 0.5378, 0.3121, 0.8038, 0.2117]])

random_tensor: torch.Size([7, 7])
tensor([[0.2398, 0.1739, 0.3253, 0.4924, 0.0557, 0.1170, 0.8122]])

second_random_tensor: torch.Size([1, 7])

second_random_tensor.T: torch.Size([7, 1])
tensor([[0.2398],
        [0.1739],
        [0.3253],
        [0.4924],
        [0.0557],
        [0.1170],
        [0.8122]])
tensor([[0.9278],
        [0.9743],
        [0.7117],
        [1.0496],
        [1.3190],
        [0.4931],
        [0.8667]])

Output shape: torch.Size([7, 1])


4. Set the random seed to 0 and do 2 & 3 over again.
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))


In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
first_tensor=torch.rand(size=(7,7))
second_tensor=torch.rand(size=(1,7))
output=torch.matmul(first_tensor, second_tensor.T)
output, output.shape
# Matrix multiply tensors

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

If there is, set the GPU random seed to 1234.

In [9]:

# Set random seed on the GPU
#torch.cuda.is_available()
#torch.cuda.device_count()
#if torch.cuda.is_available():
  #device="cuda"
#elif torch.backends.mps.is_available():
  #device="mps"
#else:
  #device="cpu"

torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [8]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
first_tensor=torch.rand(size=(2,3))
print(first_tensor, first_tensor.device)
second_tensor=torch.rand(size=(2,3))
print(second_tensor, second_tensor.device)

if torch.cuda.is_available():
  device="cuda"
elif torch.backends.mps.is_available():
  device="mps"
else:
  device="cpu"

first_tensor_on_gpu = first_tensor.to(device)
second_tensor_on_gpu = second_tensor.to(device)
print(first_tensor_on_gpu)
print(second_tensor_on_gpu)

True
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [18]:
# Perform matmul on tensor_A and tensor_B
output=torch.matmul(first_tensor,second_tensor.T)
output_on_gpu=output.to(device)

output_on_gpu,output_on_gpu.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
print(f"Minimum: {output_on_gpu.min()}")
print(f"Maximum: {output_on_gpu.max()}")
# Find min

Minimum: 0.3647301495075226
Maximum: 0.5617256760597229


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [23]:
# Set seed
torch.manual_seed(7)



# Create random tensor
first_tensor=torch.rand(size=(1,1,1,10))

# Remove single dimensions

second_tensor=first_tensor.reshape(10)

# Print out tensors and their shapes
first_tensor, first_tensor.shape, second_tensor, second_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))